version: '3.7'

services:
    db:
        build: 
            context: ./database
            dockerfile: Dockerfile
            args:
                MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
                MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
                MONGO_NON_ROOT_ROLE: ${MONGO_NON_ROOT_ROLE}
                MONGO_DB: ${MONGO_DB}
        command: ["--bind_ip_all"]
        ports:
            - 27017:27017
        restart: always
        volumes:
            - data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
            MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
            MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
        networks:
            - app-network
    api:
        build: ./api
        ports:
            - 3000:3000
        volumes:
            - ./api:/home/node
            - /home/node/node_modules
        command: ["yarn", "dev"]
        depends_on:
            - db
        environment:
            API_PORT: ${API_PORT}
            MONGO_USERNAME: ${MONGO_NON_ROOT_USERNAME}
            MONGO_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
            MONGO_HOSTNAME: ${MONGO_HOSTNAME}
            MONGO_PORT: ${MONGO_PORT}
            MONGO_DB: ${MONGO_DB}
        networks:
            - app-network
    vue:
        build: ./web
        command: ["yarn", "serve"]
        ports:
            - 8080:8080
        volumes:
            - ./web:/home/node
            - /home/node/node_modules
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data: